# Generated by Django 3.1.6 on 2021-02-21 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Athlete',
            fields=[
                ('ID', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=200, unique=True)),
                ('Sex', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=20)),
                ('Age', models.CharField(max_length=200)),
                ('Height', models.CharField(max_length=200)),
                ('Weight', models.CharField(max_length=200)),
                ('Team', models.CharField(max_length=100)),
                ('NOC', models.CharField(max_length=3)),
                ('Games', models.CharField(max_length=100)),
                ('Year', models.CharField(max_length=255)),
                ('Season', models.CharField(max_length=255)),
                ('City', models.CharField(max_length=100)),
                ('Sport', models.CharField(max_length=100)),
                ('Event', models.CharField(max_length=100)),
                ('Medal', models.CharField(choices=[('Bronze', 'Bronze'), ('Silver', 'Silver'), ('Gold', 'Gold')], max_length=200)),
            ],
        ),
    ]
