# Generated by Django 3.2.7 on 2021-09-08 00:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20210309_0110'),
    ]

    operations = [
        migrations.RenameField(
            model_name='athlete',
            old_name='Age',
            new_name='age',
        ),
        migrations.RenameField(
            model_name='athlete',
            old_name='ID',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='athlete',
            old_name='Medal',
            new_name='medal',
        ),
        migrations.RenameField(
            model_name='athlete',
            old_name='Name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='athlete',
            old_name='Sex',
            new_name='sex',
        ),
        migrations.RenameField(
            model_name='athlete',
            old_name='City',
            new_name='sport',
        ),
        migrations.RenameField(
            model_name='athlete',
            old_name='Event',
            new_name='team',
        ),
        migrations.RenameField(
            model_name='athlete',
            old_name='Season',
            new_name='year',
        ),
        migrations.RemoveField(
            model_name='athlete',
            name='Games',
        ),
        migrations.RemoveField(
            model_name='athlete',
            name='Height',
        ),
        migrations.RemoveField(
            model_name='athlete',
            name='NOC',
        ),
        migrations.RemoveField(
            model_name='athlete',
            name='Sport',
        ),
        migrations.RemoveField(
            model_name='athlete',
            name='Team',
        ),
        migrations.RemoveField(
            model_name='athlete',
            name='Weight',
        ),
        migrations.RemoveField(
            model_name='athlete',
            name='Year',
        ),
    ]
