# Generated by Django 3.2.7 on 2021-09-09 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20210908_0018'),
    ]

    operations = [
        migrations.AddField(
            model_name='athlete',
            name='noc',
            field=models.CharField(default='teste', max_length=100),
        ),
    ]
