# Generated by Django 3.2.7 on 2021-09-09 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_athlete_noc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='athlete',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
