export const COUNTRYCODE = {
    Andorra: "AD",
    "United Arab Emirates": "AE",
    Afghanistan: "AF",
    "Antigua and Barbuda": "AG",
    Anguilla: "AI",
    Akkadian: "AK",
    Abkhazian: "AH",
    Albania: "AL",
    Armenia: "AM",
    "Netherlands Antilles": "AN",
    Angola: "AO",
    Antarctica: "AQ",
    Argentina: "AR",
    "American Samoa": "AS",
    Austria: "AT",
    Australia: "AU",
    Aruba: "AW",
    "Åland Islands": "AX",
    Azerbaijan: "AZ",
    "Bosnia and Herzegovina": "BA",
    Barbados: "BB",
    Bangladesh: "BD",
    Belgium: "BE",
    "Burkina Faso": "BF",
    Bulgaria: "BG",
    Bahrain: "BH",
    Burundi: "BI",
    Benin: "BJ",
    "Saint Barthélemy": "BL",
    Bermuda: "BM",
    "Brunei Darussalam": "BN",
    Bolivia: "BO",
    "Bonaire, Sint Eustatius and Saba": "BQ",
    Brazil: "BR",
    Bahamas: "BS",
    Bhutan: "BT",
    "Bouvet Island": "BV",
    Botswana: "BW",
    Belarus: "BY",
    Belize: "BZ",
    Canada: "CA",
    "Cocos (Keeling) Islands": "CC",
    Congo: "CD",
    "Central African Republic": "CF",
    Congo: "CG",
    Switzerland: "CH",
    "Côte D'Ivoire": "CI",
    "Cook Islands": "CK",
    Chile: "CL",
    Cameroon: "CM",
    China: "CN",
    Colombia: "CO",
    "Costa Rica": "CR", 
    Cuba: "CU",
    "Cape Verde": "CV",
    Curaçao: "CW",
    "Christmas Island": "CX",
    Cyprus: "CY",
    "Czech Republic": "CZ",
    Germany: "DE",
    Djibouti: "DJ",
    Denmark: "DK",
    Dominica: "DM",
    "Dominican Republic": "DM",
    Algeria: "DZ",
    Ecuador: "EC",
    Estonia: "EE",
    Egypt: "FI",
    "Western Sahara": "EH",
    Eritrea: "ER",
    Spain:"ES",
    Ethiopia: "ET",
    "European Union": "EU",
    Finland: "FI",
    Fiji: "FJ",
    "Falkland Islands (Malvinas)": "FK",
    Micronesia: "FM",
    "Faroe Islands": "FO",
    France: "FR",
    Gabon: "GA",
    "United Kingdom": "GB",
    Grenada: "GD",
    Georgia: "GE",
    "French Guiana": "GF",
    Guernsey: "GG",
    Ghana: "GH",
    Gibraltar: "GI",
    Greenland: "GL",
    Gambia: "GM",
    Guinea: "GN",
    Guadeloupe: "GP",
    "Equatorial Guinea": "GQ",
    Greece: "GR",
    "South Georgia and the South Sandwich Islands": "GS",
    Guatemala: "GT",
    Guam: "GU",
    "Guinea-Bissau": "GW",
    Guyana: "GY",
    "Hong Kong": "HK", 
    "Heard and McDonald Islands": "HM",
    Honduras: "HN",
    Croatia: "HR",
    Haiti: "HT",
    Hungary: "HU",
    "Canary Islands": "IC",
    Indonesia: "ID",
    Ireland: "IE",
    Israel: "IL",
    "Isle of Man": "IM",
    India: "IN",
    "British Indian Ocean Territory": "IO",
    Iraq: "IQ",
    Iran: "IR",
    Iceland: "IS",
    Italy: "IT",
    Jersey: "JE",
    Jamaica: "JM",
    Jordan: "JO",
    Japan: "JP",
    Kenya: "KE",
    Kyrgyzstan: "KG",
    Cambodia: "KH",
    Kiribati: "KI",
    Comoros: "KM",
    "Saint Kitts And Nevis": "KN",
    "Korea, Democratic People's Republic Of": "KP",
    Korea: "KR",
    Kuwait: "KW",
    "Cayman Islands": "KY",
    Kazakhstan: "KZ",
    "Lao People's Democratic Republic": "LA",
    Lebanon: "LB",
    Saint: "LC",
    Liechtenstein: "LI",
    "Sri Lanka": "LK",
    Liberia: "LR",
    Lesotho: "LS",
    Lithuania: "LT",
    Luxembourg: "LU",
    Latvia: "LV",
    Libya: "LY",
    Morocco: "MA",
    Monaco: "MC",
    Moldova: "MD",
    Montenegro: "ME",
    "Saint Martin": "MF",
    Madagascar: "MG",
    "Marshall Islands": "MH",
    Macedonia: "MK",
    Mali: "ML",
    Myanmar: "MM",
    Mongolia: "MN",
    Macao: "MO",
    "Northern Mariana Islands": "MP",
    Martinique: "MQ",
    Mauritania: "MR",
    Montserrat: "MS",
    Malta: "MT",
    Mauritius: "MU",
    Maldives: "MV",
    Malawi: "MW",
    Mexico: "MX"

    
}