export const TEAM = {
    REGIAO: [
        'Afghanistan',
        'Curacao',
        'Albania',
        'Algeria',
        'Andorra',
        'Angola',
        'Antigua',
        'Australia',
        'Argentina',
        'Armenia',
        'Aruba',
        'American Samoa',
        'Azerbaijan',
        'Bahamas',
        'Bangladesh',
        'Barbados',
        'Burundi',
        'Benin',
        'Bermuda',
        'Bhutan',
        'Bosnia and Herzegovina',
        'Belize',
        'Belarus',
        'Czech Republic',
        'Boliva',
        'Botswana',
        'Brazil',
        'Bahrain',
        'Brunei',
        'Bulgaria',
        'Burkina Faso',
        'Central African Republic',
        'Cambodia',
        'Canada',
        'Cayman Islands',
        'Republic of Congo',
        'Chad',
        'Chile',
        'China',
        'Ivory Coast',
        'Cameroon',
        'Democratic Republic of the Congo',
        'Cook Islands',
        'Colombia',
        'Comoros',
        'Cape Verde',
        'Costa Rica',
        'Croatia',
        'Greece',
        'Cuba',
        'Cyprus',        
        'Denmark',
        'Djibouti',
        'Dominica',
        'Dominican Republic',
        'Ecuador',
        'Egypt',
        'Eritrea',
        'El Salvador',
        'Spain',
        'Estonia',
        'Ethiopia',
        'Russia',
        'Fiji',
        'Finland',
        'France',
        'Germany',
        'Micronesia',
        'Gabon',
        'Gambia',
        'UK',
        'Guinea-Bissau',
        'Georgia',
        'Equatorial Guinea',
        'Ghana',
        'Guatemala',
        'Guinea',
        'Grenada',
        'Guam',
        'Guyana',
        'Haiti',
        'Honduras',
        'Indonesia',
        'India',
        'Individual Olympic Athletes',
        'Iran',
        'Ireland',
        'Iraq',
        'Iceland',
        'Israel',
        'Virgin Islands, US',
        'Italy',
        'Virgin Islands, British',
        'Jamaica',
        'Jordan',
        'Japan',
        'Kazakhstan',
        'Kenya',
        'Kyrgyzstan',
        'Kiribati',
        'South Korea',
        'Kosovo',
        'Saudi Arabia',
        'Kuwait',
        'Laos',
        'Latvia',
        'Libya',
        'Liberia',
        'Saint Lucia',
        'Lesotho',
        'Lebanon',
        'Liechtenstein',
        'Lithuania',
        'Luxembourg',
        'Madagascar',
        'Malaysia',
        'Morocco',
        'Malawi',
        'Moldova',
        'Maldives',
        'Mexico',
        'Mongolia',
        'Marshall Islands',
        'Macedonia',
        'Mali',
        'Malta',
        'Montenegro',
        'Monaco',
        'Mozambique',
        'Mauritius',
        'Myanmar',
        'Namibia',
        'Nicaragua',
        'Netherlands',
        'Nepal',
        'Nigeria',
        'Niger',
        'Norway',
        'Nauru',
        'New Zealand',
        'Oman',
        'Pakistan',
        'Panama',
        'Paraguay',
        'Peru',
        'Philippines',
        'Palestine',
        'Palau',
        'Papua New Guinea',
        'Poland',
        'North Korea',
        'Portugal',
        'Puerto Rico',
        'Qatar',
        'Romania',
        'South Africa',
        'Rwanda',
        'Samoa',
        'Senegal',
        'Seychelles',
        'Singapore',
        'Saint Kitts',
        'Sierra Leone',
        'Slovenia',
        'San Marino',
        'Solomon Islands',
        'Somalia',
        'Serbia',
        'Sri Lanka',
        'South Sudan',
        'Sao Tome and Principe',
        'Sudan',
        'Switzerland',
        'Suriname',
        'Slovakia',
        'Sweden',
        'Swaziland',
        'Tanzania',
        'Tonga',
        'Thailand',
        'Tajikistan',
        'Turkmenistan',
        'Timor-Leste',
        'Togo',
        'Taiwan',        'Tunisia',
        'Turkey',
        'NA',
        'United Arab Emirates',
        'Syria',
        'Uganda',
        'Uruguay',
        'USA',
        'Uzbekistan',
        'Vanuatu',
        'Venezuela',
        'Vietnam',
        'Saint Vincent',
        'Trinidad',
        'Yemen',
        'Zambia',
        'Zimbabwe',
    ],
};